from setuptools import setup, find_packages

setup(
    name="json2tree",
    version="0.2.0",
    description="Python package to create html tree view for json files, usable as CLI or library.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/abhaykatheria/json2tree",
    author="Abhay Katheria, Mithilesh Tiwari, and AI Contributor",
    author_email="abhay.katheria1998@gmail.com",
    license="MIT",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "License :: OSI Approved :: MIT License",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Text Processing :: Markup :: HTML",
        "Topic :: Utilities",
    ],
    entry_points={"console_scripts": ["json2tree=json2tree.__main__:main"]},
)
